# Generated by Django 4.2.1 on 2023-06-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.CharField(default='Hello! :D', max_length=240),
        ),
    ]
